with open('C:/Users/000/.openclaw/workspace/cfp-malaysia/app/insurance/page.tsx', 'rb') as f:
    data = f.read()
lines = data.split(b'\n')

# Replace lines 999-1041 (0-indexed: 998-1040)
new_section = []
new_section.append(b' </div>\r')
new_section.append(b' <div>\r')
new_section.append(b'  <label className="text-xs text-gray-600 mb-1 block">Existing Policies (optional)</label>\r')
new_section.append(b'  {existingPolicies.length > 0 && (\r')
new_section.append(b'  <table className="w-full text-xs mb-2 border border-gray-200 rounded-lg overflow-hidden">\r')
new_section.append(b'  <thead><tr className="bg-gray-50 border-b border-gray-200">\r')
new_section.append(b'  <th className="text-left px-2 py-1 font-medium text-gray-600">Policy Type</th>\r')
new_section.append(b'  <th className="text-left px-2 py-1 font-medium text-gray-600">Sum Assured (RM)</th>\r')
new_section.append(b'  <th className="text-left px-2 py-1 font-medium text-gray-600">Premium (RM/mo)</th>\r')
new_section.append(b'  <th className="w-8"></th>\r')
new_section.append(b'  </tr></thead>\r')
new_section.append(b'  <tbody>{existingPolicies.map((p, i) => (\r')
new_section.append(b'  <tr key={i} className="border-b border-gray-100">\r')
new_section.append(b'  <td className="px-1 py-1">\r')
new_section.append(b'  <select value={p.policyType} onChange={e => { const updated = [...existingPolicies]; updated[i].policyType = e.target.value; setExistingPolicies(updated); }} className="w-full border border-gray-200 rounded px-1 py-1 bg-white focus:outline-none" style={{color:"#111827"}}>\r')
new_section.append(b'  <option value="">Select</option>\r')
new_section.append(b'  <option value="Life">Life</option>\r')
new_section.append(b'  <option value="CI">CI</option>\r')
new_section.append(b'  <option value="Medical">Medical</option>\r')
new_section.append(b'  <option value="Savings">Savings</option>\r')
new_section.append(b'  <option value="Others">Others</option>\r')
new_section.append(b'  </select>\r')
new_section.append(b'  </td>\r')
new_section.append(b'  <td className="px-1 py-1">\r')
new_section.append(b'  <input type="number" value={p.sumAssured || ""} onChange={e => { const updated = [...existingPolicies]; updated[i].sumAssured = parseInt(e.target.value) || 0; setExistingPolicies(updated); }} placeholder="0" className="w-full border border-gray-200 rounded px-1 py-1 focus:outline-none" style={{color:"#111827"}} />\r')
new_section.append(b'  </td>\r')
new_section.append(b'  <td className="px-1 py-1">\r')
new_section.append(b'  <input type="number" value={p.premium || ""} onChange={e => { const updated = [...existingPolicies]; updated[i].premium = parseInt(e.target.value) || 0; setExistingPolicies(updated); }} placeholder="0" className="w-full border border-gray-200 rounded px-1 py-1 focus:outline-none" style={{color:"#111827"}} />\r')
new_section.append(b'  </td>\r')
new_section.append(b'  <td className="px-1 py-1 text-center">\r')
new_section.append(b'  <button onClick={() => setExistingPolicies(existingPolicies.filter((_, j) => j !== i))} className="text-red-400 hover:text-red-600 text-xs">X</button>\r')
new_section.append(b'  </td>\r')
new_section.append(b'  </tr>\r')
new_section.append(b'  ))}</tbody>\r')
new_section.append(b'  </table>\r')
new_section.append(b'  )}\r')
new_section.append(b'  <button onClick={() => setExistingPolicies([...existingPolicies, { policyType: "", sumAssured: 0, premium: 0 }])} className="text-xs text-indigo-600 hover:text-indigo-800 font-medium">+ Add Policy</button>\r')
new_section.append(b' </div>\r')
new_section.append(b' {/* Start Analysis button */}\r')

new_lines = lines[:998] + new_section + lines[1041:]

with open('C:/Users/000/.openclaw/workspace/cfp-malaysia/app/insurance/page.tsx', 'wb') as f:
    f.write(b'\n'.join(new_lines))

print(f'Done. New line count: {len(new_lines)}')
print(f'Old line count: {len(lines)}')
