/**
 * Seed script — Malaysian Investment & Insurance Products
 * Run: npm run seed:products
 */

import { getDb } from '../lib/db/client';
import { investmentProducts, insuranceProducts } from '../lib/db/schema';

function uid() {
  return crypto.randomUUID();
}

function now() {
  return Math.floor(Date.now() / 1000);
}

const INVESTMENT_PRODUCTS = [
  // ── Equity (Growth) ────────────────────────────────────────────────────────
  {
    productCode: 'KENANGA-GROWTH',
    productName: 'Kenanga Growth Fund',
    provider: 'Kenanga Investors Berhad',
    category: 'equity',
    riskRating: '4',
    fundSize: 320_000_000,
    managementFee: 1.5,
    salesCharge: 3.0,
    navPerUnit: 0.542,
    oneYearReturn: 8.4,
    isShariahCompliant: false,
  },
  {
    productCode: 'KENANGA-SYARIAH-GROWTH',
    productName: 'Kenanga Syariah Growth Fund',
    provider: 'Kenanga Investors Berhad',
    category: 'equity_shariah',
    riskRating: '4',
    fundSize: 180_000_000,
    managementFee: 1.5,
    salesCharge: 3.0,
    navPerUnit: 0.618,
    oneYearReturn: 7.2,
    isShariahCompliant: true,
  },
  {
    productCode: 'PUBLIC-ISLAMIC-EQUITY',
    productName: 'Public Islamic Equity Fund',
    provider: 'Public Mutual Berhad',
    category: 'equity_shariah',
    riskRating: '4',
    fundSize: 450_000_000,
    managementFee: 1.6,
    salesCharge: 3.0,
    navPerUnit: 1.234,
    oneYearReturn: 6.8,
    isShariahCompliant: true,
  },
  {
    productCode: 'PUBLIC-SMALL-CAP',
    productName: 'Public SmallCap Fund',
    provider: 'Public Mutual Berhad',
    category: 'equity',
    riskRating: '5',
    fundSize: 95_000_000,
    managementFee: 1.7,
    salesCharge: 3.0,
    navPerUnit: 0.387,
    oneYearReturn: 12.1,
    isShariahCompliant: false,
  },
  {
    productCode: 'PMB-SYARIAH-GROWTH',
    productName: 'PMB Shariah Growth Fund',
    provider: 'PMB Investment Berhad',
    category: 'equity_shariah',
    riskRating: '4',
    fundSize: 140_000_000,
    managementFee: 1.5,
    salesCharge: 3.0,
    navPerUnit: 0.721,
    oneYearReturn: 7.6,
    isShariahCompliant: true,
  },
  {
    productCode: 'AFFIN-SELECT-ASIA',
    productName: 'Affin Hwang Select Asia Fund',
    provider: 'Affin Hwang Asset Management Berhad',
    category: 'equity',
    riskRating: '5',
    fundSize: 210_000_000,
    managementFee: 1.8,
    salesCharge: 5.0,
    navPerUnit: 0.445,
    oneYearReturn: 9.3,
    isShariahCompliant: false,
  },
  {
    productCode: 'RHB-ASIAN-GROWTH',
    productName: 'RHB Asian Growth Fund',
    provider: 'RHB Asset Management Sdn Bhd',
    category: 'equity',
    riskRating: '4',
    fundSize: 175_000_000,
    managementFee: 1.75,
    salesCharge: 5.0,
    navPerUnit: 0.558,
    oneYearReturn: 7.9,
    isShariahCompliant: false,
  },
  {
    productCode: 'CIMB-SMA-GROWTH',
    productName: 'CIMB Smart Growth Fund',
    provider: 'CIMB-Principal Asset Management',
    category: 'equity',
    riskRating: '4',
    fundSize: 260_000_000,
    managementFee: 1.6,
    salesCharge: 3.0,
    navPerUnit: 0.689,
    oneYearReturn: 8.1,
    isShariahCompliant: false,
  },
  {
    productCode: 'HONGLEONG-GROWTH',
    productName: 'Hong Leong Growth Fund',
    provider: 'Hong Leong Asset Management Bhd',
    category: 'equity',
    riskRating: '4',
    fundSize: 130_000_000,
    managementFee: 1.5,
    salesCharge: 3.0,
    navPerUnit: 2.341,
    oneYearReturn: 7.4,
    isShariahCompliant: false,
  },
  {
    productCode: 'AMBANK-GROWTH',
    productName: 'AmGrowth Fund',
    provider: 'AmAsset Management Sdn Bhd',
    category: 'equity',
    riskRating: '4',
    fundSize: 155_000_000,
    managementFee: 1.6,
    salesCharge: 3.0,
    navPerUnit: 0.423,
    oneYearReturn: 8.7,
    isShariahCompliant: false,
  },

  // ── Balanced / Mixed ──────────────────────────────────────────────────────
  {
    productCode: 'KENANGA-BALANCED',
    productName: 'Kenanga Balanced Growth Fund',
    provider: 'Kenanga Investors Berhad',
    category: 'balanced',
    riskRating: '3',
    fundSize: 95_000_000,
    managementFee: 1.3,
    salesCharge: 2.5,
    navPerUnit: 0.781,
    oneYearReturn: 6.2,
    isShariahCompliant: false,
  },
  {
    productCode: 'PUBLIC-BALANCED',
    productName: 'Public Balanced Fund',
    provider: 'Public Mutual Berhad',
    category: 'balanced',
    riskRating: '3',
    fundSize: 280_000_000,
    managementFee: 1.3,
    salesCharge: 2.5,
    navPerUnit: 1.892,
    oneYearReturn: 5.8,
    isShariahCompliant: false,
  },
  {
    productCode: 'RHB-BALANCED',
    productName: 'RHB Balanced Fund',
    provider: 'RHB Asset Management Sdn Bhd',
    category: 'balanced',
    riskRating: '3',
    fundSize: 110_000_000,
    managementFee: 1.4,
    salesCharge: 2.5,
    navPerUnit: 1.023,
    oneYearReturn: 5.5,
    isShariahCompliant: false,
  },

  // ── Income / Bond ─────────────────────────────────────────────────────────
  {
    productCode: 'KENANGA-INCOME',
    productName: 'Kenanga Income Plus Fund',
    provider: 'Kenanga Investors Berhad',
    category: 'bond',
    riskRating: '2',
    fundSize: 420_000_000,
    managementFee: 1.0,
    salesCharge: 1.5,
    navPerUnit: 0.987,
    oneYearReturn: 4.2,
    isShariahCompliant: false,
  },
  {
    productCode: 'PUBLIC-FIXED-INCOME',
    productName: 'Public Fixed Income Fund',
    provider: 'Public Mutual Berhad',
    category: 'bond',
    riskRating: '2',
    fundSize: 550_000_000,
    managementFee: 1.0,
    salesCharge: 1.5,
    navPerUnit: 1.123,
    oneYearReturn: 4.0,
    isShariahCompliant: false,
  },
  {
    productCode: 'CIMB-INCOME',
    productName: 'CIMB Islamic Income Fund',
    provider: 'CIMB-Principal Asset Management',
    category: 'bond_shariah',
    riskRating: '2',
    fundSize: 310_000_000,
    managementFee: 1.0,
    salesCharge: 1.5,
    navPerUnit: 1.045,
    oneYearReturn: 3.9,
    isShariahCompliant: true,
  },

  // ── Money Market ───────────────────────────────────────────────────────────
  {
    productCode: 'RHB-CASH-MGMT',
    productName: 'RHB Cash Management Fund',
    provider: 'RHB Asset Management Sdn Bhd',
    category: 'money_market',
    riskRating: '1',
    fundSize: 890_000_000,
    managementFee: 0.5,
    salesCharge: 0.0,
    navPerUnit: 1.001,
    oneYearReturn: 2.8,
    isShariahCompliant: false,
  },
  {
    productCode: 'KENANGA-MONEY-MARKET',
    productName: 'Kenanga Money Market Fund',
    provider: 'Kenanga Investors Berhad',
    category: 'money_market',
    riskRating: '1',
    fundSize: 620_000_000,
    managementFee: 0.5,
    salesCharge: 0.0,
    navPerUnit: 1.000,
    oneYearReturn: 2.7,
    isShariahCompliant: false,
  },

  // ── PRS (Private Retirement Scheme) ──────────────────────────────────────
  {
    productCode: 'PRINCIPAL-PRS-PLUS-GROWTH',
    productName: 'Principal PRS Plus Growth Fund',
    provider: 'Principal Asset Management Berhad',
    category: 'prs',
    riskRating: '4',
    fundSize: 75_000_000,
    managementFee: 1.2,
    salesCharge: 0.0,
    navPerUnit: 0.834,
    oneYearReturn: 7.8,
    isShariahCompliant: false,
  },
  {
    productCode: 'PRINCIPAL-PRS-PLUS-CONSERVATIVE',
    productName: 'Principal PRS Plus Conservative Fund',
    provider: 'Principal Asset Management Berhad',
    category: 'prs',
    riskRating: '2',
    fundSize: 45_000_000,
    managementFee: 1.0,
    salesCharge: 0.0,
    navPerUnit: 0.956,
    oneYearReturn: 3.5,
    isShariahCompliant: false,
  },
  {
    productCode: 'SCHRODER-PRS-GROWTH',
    productName: 'Schroder PRS Growth Fund',
    provider: 'Schroder Investment Management Berhad',
    category: 'prs',
    riskRating: '4',
    fundSize: 55_000_000,
    managementFee: 1.3,
    salesCharge: 0.0,
    navPerUnit: 0.712,
    oneYearReturn: 8.2,
    isShariahCompliant: false,
  },
  {
    productCode: 'MANULIFE-PRS-GROWTH',
    productName: 'Manulife PRS Growth Fund',
    provider: 'Manulife Investment Management Berhad',
    category: 'prs',
    riskRating: '4',
    fundSize: 68_000_000,
    managementFee: 1.25,
    salesCharge: 0.0,
    navPerUnit: 0.778,
    oneYearReturn: 7.5,
    isShariahCompliant: false,
  },
  {
    productCode: 'AFFIN-PRS-GROWTH',
    productName: 'Affin Hwang PRS Growth Fund',
    provider: 'Affin Hwang Asset Management Berhad',
    category: 'prs',
    riskRating: '4',
    fundSize: 42_000_000,
    managementFee: 1.3,
    salesCharge: 0.0,
    navPerUnit: 0.645,
    oneYearReturn: 7.1,
    isShariahCompliant: false,
  },
  {
    productCode: 'SUNLIFE-PRS-GROWTH',
    productName: 'Sun Life PRS Growth Fund',
    provider: 'Sun Life Malaysia Assurance Berhad',
    category: 'prs',
    riskRating: '3',
    fundSize: 38_000_000,
    managementFee: 1.2,
    salesCharge: 0.0,
    navPerUnit: 0.823,
    oneYearReturn: 6.4,
    isShariahCompliant: false,
  },

  // ── Shariah Funds ──────────────────────────────────────────────────────────
  {
    productCode: 'KAFF-SHARIAH-GROWTH',
    productName: 'KAF-S Shariah Growth Fund',
    provider: 'KAF Investment Fund Managers Sdn Bhd',
    category: 'equity_shariah',
    riskRating: '4',
    fundSize: 88_000_000,
    managementFee: 1.55,
    salesCharge: 3.0,
    navPerUnit: 0.534,
    oneYearReturn: 7.0,
    isShariahCompliant: true,
  },
  {
    productCode: 'BIMB-SHARIAH-GROWTH',
    productName: 'BIMB Shariah Growth Fund',
    provider: 'BIMB Investment Management Berhad',
    category: 'equity_shariah',
    riskRating: '4',
    fundSize: 125_000_000,
    managementFee: 1.5,
    salesCharge: 3.0,
    navPerUnit: 0.678,
    oneYearReturn: 6.5,
    isShariahCompliant: true,
  },

  // ── ETFs ──────────────────────────────────────────────────────────────────
  {
    productCode: 'ASYIK-EFT-MY50',
    productName: 'ASYIK ETF MY50',
    provider: 'ASYA Capital Malaysia Berhad',
    category: 'etf',
    riskRating: '3',
    fundSize: 50_000_000,
    managementFee: 0.3,
    salesCharge: 0.0,
    navPerUnit: 5.12,
    oneYearReturn: 7.8,
    isShariahCompliant: false,
  },
  {
    productCode: 'SINGA-EFT',
    productName: 'Singa ETF',
    provider: 'Supervised by Securities Commission Malaysia',
    category: 'etf',
    riskRating: '4',
    fundSize: 35_000_000,
    managementFee: 0.4,
    salesCharge: 0.0,
    navPerUnit: 4.23,
    oneYearReturn: 9.5,
    isShariahCompliant: false,
  },
  {
    productCode: 'GTALPHA-EFT',
    productName: 'GTAlpha ETF',
    provider: 'Securities Commission Malaysia',
    category: 'etf',
    riskRating: '4',
    fundSize: 28_000_000,
    managementFee: 0.5,
    salesCharge: 0.0,
    navPerUnit: 3.87,
    oneYearReturn: 11.2,
    isShariahCompliant: false,
  },

  // ── More Equity Funds ────────────────────────────────────────────────────
  {
    productCode: 'PHILLIP-GROWTH',
    productName: 'Phillip Master Equity Fund',
    provider: 'Phillip Mutual Berhad',
    category: 'equity',
    riskRating: '4',
    fundSize: 72_000_000,
    managementFee: 1.6,
    salesCharge: 3.0,
    navPerUnit: 0.456,
    oneYearReturn: 8.9,
    isShariahCompliant: false,
  },
  {
    productCode: 'MIDF-GROWTH',
    productName: 'MIDF Equity Fund',
    provider: 'MIDF Amanah Investment Bank Berhad',
    category: 'equity',
    riskRating: '4',
    fundSize: 105_000_000,
    managementFee: 1.55,
    salesCharge: 3.0,
    navPerUnit: 0.891,
    oneYearReturn: 7.7,
    isShariahCompliant: false,
  },
];

const INSURANCE_PRODUCTS = [
  // ── Takaful (Shariah) ────────────────────────────────────────────────────
  {
    productCode: 'ETIQA-FAMILY-TAKAFUL',
    productName: 'Etiqa Family Takaful',
    provider: 'Etiqa Family Takaful Berhad',
    policyType: 'family_takaful',
    monthlyPremiumMin: 150,
    coverageAmountMax: 1_000_000,
    isTakaful: true,
  },
  {
    productCode: 'ETIQA-CRITICAL-ILLNESS',
    productName: 'Etiqa Critical Illness Takaful',
    provider: 'Etiqa Family Takaful Berhad',
    policyType: 'critical_illness',
    monthlyPremiumMin: 100,
    coverageAmountMax: 500_000,
    isTakaful: true,
  },
  {
    productCode: 'ETIQA-MEDICAL',
    productName: 'Etiqa Medical & Health Takaful',
    provider: 'Etiqa Family Takaful Berhad',
    policyType: 'medical',
    monthlyPremiumMin: 200,
    coverageAmountMax: 300_000,
    isTakaful: true,
  },
  {
    productCode: 'GREAT-EASTERN-TAKAFUL',
    productName: 'Great Eastern Family Takaful',
    provider: 'Great Eastern Takaful Berhad',
    policyType: 'family_takaful',
    monthlyPremiumMin: 180,
    coverageAmountMax: 800_000,
    isTakaful: true,
  },
  {
    productCode: 'TAKAFUL-PRS-PLUS',
    productName: 'Takaful PRS Plus Plan',
    provider: 'Takaful Malaysia Berhad',
    policyType: 'prs',
    monthlyPremiumMin: 100,
    coverageAmountMax: 0,
    isTakaful: true,
  },

  // ── Conventional Life ────────────────────────────────────────────────────
  {
    productCode: 'ETIQA-LIFE',
    productName: 'Etiqa Life Insurance',
    provider: 'Etiqa Life Insurance Berhad',
    policyType: 'life',
    monthlyPremiumMin: 120,
    coverageAmountMax: 750_000,
    isTakaful: false,
  },
  {
    productCode: 'PRUDENTIAL-PRULINK-MILLION',
    productName: 'PRULink Million',
    provider: 'Prudential Malaysia',
    policyType: 'investment_linked',
    monthlyPremiumMin: 300,
    coverageAmountMax: 2_000_000,
    isTakaful: false,
  },
  {
    productCode: 'PRUDENTIAL-PRUESSENTIAL-HEALTH',
    productName: 'PRUessential Health',
    provider: 'Prudential Malaysia',
    policyType: 'medical',
    monthlyPremiumMin: 250,
    coverageAmountMax: 500_000,
    isTakaful: false,
  },
  {
    productCode: 'PRUDENTIAL-PRULINK-ACCELERATOR',
    productName: 'PRULink Accelerator',
    provider: 'Prudential Malaysia',
    policyType: 'investment_linked',
    monthlyPremiumMin: 500,
    coverageAmountMax: 1_500_000,
    isTakaful: false,
  },
  {
    productCode: 'GREAT-EASTERN-GREAT-SECURE',
    productName: 'Great Secure',
    provider: 'Great Eastern Life Assurance Berhad',
    policyType: 'life',
    monthlyPremiumMin: 150,
    coverageAmountMax: 600_000,
    isTakaful: false,
  },
  {
    productCode: 'GREAT-EASTERN-SMART-MEDIC',
    productName: 'Smart Medic',
    provider: 'Great Eastern General Insurance Berhad',
    policyType: 'medical',
    monthlyPremiumMin: 180,
    coverageAmountMax: 400_000,
    isTakaful: false,
  },
  {
    productCode: 'GREAT-EASTERN-LIFE-CARE',
    productName: 'Great Life Care',
    provider: 'Great Eastern Life Assurance Berhad',
    policyType: 'medical',
    monthlyPremiumMin: 220,
    coverageAmountMax: 600_000,
    isTakaful: false,
  },
  {
    productCode: 'AIA-A-LIFE-SIGNATURE',
    productName: 'A-Life Signature',
    provider: 'AIA Malaysia',
    policyType: 'life',
    monthlyPremiumMin: 200,
    coverageAmountMax: 1_000_000,
    isTakaful: false,
  },
  {
    productCode: 'AIA-MEDICAL-PLUS',
    productName: 'Medical Plus',
    provider: 'AIA Malaysia',
    policyType: 'medical',
    monthlyPremiumMin: 230,
    coverageAmountMax: 500_000,
    isTakaful: false,
  },
  {
    productCode: 'AIA-CRITICAL-ILLNESS',
    productName: 'AIA Critical Illness Cover',
    provider: 'AIA Malaysia',
    policyType: 'critical_illness',
    monthlyPremiumMin: 130,
    coverageAmountMax: 400_000,
    isTakaful: false,
  },
  {
    productCode: 'ALLIANZ-LIFE-INSURANCE',
    productName: 'Allianz Life Insurance',
    provider: 'Allianz Malaysia Berhad',
    policyType: 'life',
    monthlyPremiumMin: 140,
    coverageAmountMax: 700_000,
    isTakaful: false,
  },
  {
    productCode: 'ALLIANZ-MEDICAL-PLAN',
    productName: 'Allianz Medical Plan',
    provider: 'Allianz Malaysia Berhad',
    policyType: 'medical',
    monthlyPremiumMin: 210,
    coverageAmountMax: 450_000,
    isTakaful: false,
  },
  {
    productCode: 'ALLIANZ-PERSONAL-ACCIDENT',
    productName: 'Allianz Personal Accident',
    provider: 'Allianz Malaysia Berhad',
    policyType: 'personal_accident',
    monthlyPremiumMin: 50,
    coverageAmountMax: 200_000,
    isTakaful: false,
  },
  {
    productCode: 'TUNEPROOF-DISABILITY',
    productName: 'Tune Protect Disability Income',
    provider: 'Tune Insurance Malaysia Berhad',
    policyType: 'disability',
    monthlyPremiumMin: 80,
    coverageAmountMax: 10_000,
    isTakaful: false,
  },
  {
    productCode: 'SONY-CREDIT-PROTECTION',
    productName: 'Zurich Credit Protection Plan',
    provider: 'Zurich Insurance Malaysia Berhad',
    policyType: 'life',
    monthlyPremiumMin: 60,
    coverageAmountMax: 100_000,
    isTakaful: false,
  },
  {
    productCode: 'ABERDEEN-LIFE',
    productName: 'Manulife Life Cover',
    provider: 'Manulife Insurance Berhad',
    policyType: 'life',
    monthlyPremiumMin: 130,
    coverageAmountMax: 650_000,
    isTakaful: false,
  },
  {
    productCode: 'HLA-LIFE-PROTECTOR',
    productName: 'HLA Life Protector',
    provider: 'Hong Leong Assurance Berhad',
    policyType: 'life',
    monthlyPremiumMin: 110,
    coverageAmountMax: 550_000,
    isTakaful: false,
  },
  {
    productCode: 'MPI-PERSONAL-ACCIDENT',
    productName: 'MPI Personal Accident Insurance',
    provider: 'MPI Insurance Berhad',
    policyType: 'personal_accident',
    monthlyPremiumMin: 40,
    coverageAmountMax: 150_000,
    isTakaful: false,
  },
];

async function seed() {
  const db = getDb();

  console.log('🌱 Seeding Malaysian investment products...\n');

  for (const p of INVESTMENT_PRODUCTS) {
    await db.insert(investmentProducts).values({
      id: uid(),
      ...p,
      lastUpdated: now(),
    }).onConflictDoNothing();
    console.log(`  ✅ ${p.productCode} — ${p.productName}`);
  }

  console.log(`\n🌱 Seeding Malaysian insurance products...\n`);

  for (const p of INSURANCE_PRODUCTS) {
    await db.insert(insuranceProducts).values({
      id: uid(),
      ...p,
      lastUpdated: now(),
    }).onConflictDoNothing();
    console.log(`  ✅ ${p.productCode} — ${p.productName}`);
  }

  console.log(`\n✅ Seeded ${INVESTMENT_PRODUCTS.length} investment products + ${INSURANCE_PRODUCTS.length} insurance products`);
}

seed().catch(console.error);
